name: Deploy to Kubernetes

on:
  push:
    branches:
      - kustomize

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  OIDC_ROLE_ARN: ${{ secrets.OIDC_ROLE }}
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

permissions:
      id-token: write
      contents: write
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: write    # This is required for actions/checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar
        
      - name: Docker build
        run: docker build -t core-service .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: GitHubActions
        role-to-assume: ${{ env.OIDC_ROLE_ARN }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Checkout for Kustomize repository
      uses: actions/checkout@v2
      with:
        repository: Project-Catcher/core-service-kusto
        ref: main
        token: ${{ env.GITHUB_TOKEN }}
        path: core-service-kusto

    - name: Update Kustomize image
      run: |
        KUSTOMIZE_PATH="core-service-kusto/overlays/dev"
        FILE_NAME="deployment.yaml"

        # Docker 이미지 URL 설정
        cd $KUSTOMIZE_PATH
        kustomize edit set image catcher-core-image="${{ steps.login-ecr.outputs.registry }}:${{ github.sha }}"
        kustomize build .
        cat kustomization.yaml
        
    # 수정된 파일 commit & push
    - name: Commit minifest files
      run: |
        cd catcher-core-kusto
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git commit -am "Update image tag"
        git push -u origin main
