name: Java CI with Gradle

on:
  pull_request:
    branches: [ "Taein2-patch-1" ]

env:
  ecr_url: ${{ secrets.ECR_REPO_DEV }}
  role_arn: ${{ secrets.OIDC_ROLE }}
  aws_region: ${{ secrets.AWS_REGION }}

permissions:
      id-token: write
      contents: read
      
jobs:
  build:
    name: Build
    runs-on: self-hosted

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar
        
      - name: Docker build
        run: docker build -t core-service .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.aws_region }}
          role-session-name: GitHubActions
          role-to-assume: ${{ env.role_arn }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish Image to ECR(CORE-SERVICE)
        run: |
          # docker tag core-service:latest ${{ env.ecr_url }}:core-service
          # docker push ${{ env.ecr_url }}:core-service
          docker tag core-service:latest ${{ env.ecr_url }}:${{ github.sha }}
          docker push ${{ env.ecr_url }}:${{ github.sha }}

      - name: Edit kustomize file
        run: |
          cd ./kustomize/overlays/dev/
          kustomize edit set image catcher-core-image=${{ env.ecr_url }}:${{ github.sha }}
          kustomize build .
          cat kustomization.yaml
          kustomize build overlays/dev/ | kubectl apply -f -

      # - name: Commit and Push files
      #   run: |
      #     cd ../..
      #     git add -A
      #     git commit -m "test commit from runner"
      #     git push origin kustomize