name: Code Review

permissions:
  contents: read
  pull-requests: write

env:
  webhook_url: ${{ secrets.WEBHOOK }}

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          MODEL: gpt-3.5-turbo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
      
      # - name: notification to swit
      #   uses: roharon/action-swit@v1
      #   with:
      #     webhooks_url: ${{ env.webhook_url }}
      #     MESSAGE: "🏷 ${{ job.status }} 백엔드 OpenAI 코드 리뷰 : Core-service - by ${{ github.actor }}"