name: CI Test

on:
  push:
    branches: [ "githubaction" ]

env:
  ecr_url: ${{ secrets.ECR_REPO_DEV }}
  role_arn: ${{ secrets.OIDC_ROLE }}
  aws_region: ${{ secrets.AWS_REGION }}
  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-region: ${{ env.aws_region }}
      #     role-session-name: GitHubActions
      #     role-to-assume: ${{ env.role_arn }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.aws_access_key }}
          aws-secret-access-key: ${{ env.aws_secret_key }}
          aws-region: ${{ env.aws_region }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml
          
