name: CI Test

on:
  pull_request:
    branches: [ main ]

env:
  aws_region: ${{ secrets.AWS_REGION }}
  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  default_output: ${{ secrets.AWS_DEFAULT_OUTPUT }}
  webhook_url: ${{ secrets.WEBHOOK }}

permissions: write-all

jobs:
  build:
    name: Build and Test
    runs-on: self-hosted
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ env.aws_access_key }}
          aws configure set aws_secret_access_key ${{ env.aws_secret_key }}
          aws configure set default.region ${{ env.aws_region }}
          aws configure set default.output ${{ env.default_output }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: build/test-results/**/*.xml

      - name: notification to swit
        uses: roharon/action-swit@v1
        with:
          webhooks_url: ${{ env.webhook_url }}
          MESSAGE: "🏷 ${{ job.status }} 백엔드 Unit Test : Core-service - by ${{ github.actor }}"